/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgautopayment;

import java.util.ArrayList;

/**
 *
 * @author elitzageorgieva
 */
public class AutoPayUI extends javax.swing.JFrame {

    /**
     * Creates new form AutoPayUI
     */
    
    public int currentAutoPayment=0;
    int selectedRow;
    ArrayList<AutoPayment> list;
    AutoPayment autoPayment;
    AutoPaymentList apl=new AutoPaymentList();
    
    /**
    * Submit button
    * Gets the text entered in the three fields by the user for routing number,
    * bank account number, and payment amount and adds to the arrayList AutoPaymentList.
    */
    
    public AutoPayUI(ArrayList<AutoPayment> list) {
        this.list=list;
        initComponents();
        routingNumberText.setText(list.get(currentAutoPayment).getRoutingNumber());
        accountNumberText.setText(list.get(currentAutoPayment).getBankAccountNumber());
        autoPayAmountText.setText(list.get(currentAutoPayment).getPaymentAmount());
    }
    
         public AutoPayUI(AutoPaymentCntl autoPayCntl, int row) 
        {
            this.list=autoPayCntl.getList();
            selectedRow=row;
            //currentConcert=row;
            autoPayment=autoPayCntl.getAutoPay(row);
            initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        routingNumberText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        accountNumberText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        autoPayAmountText = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Set Up Automatic Payment");

        jLabel2.setText("Routing Number: ");

        routingNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routingNumberTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Account Number: ");

        accountNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumberTextActionPerformed(evt);
            }
        });

        jLabel4.setText("Auto Pay Amount: $");

        autoPayAmountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoPayAmountTextActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(routingNumberText)
                                    .addComponent(accountNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(autoPayAmountText))))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(routingNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(accountNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(autoPayAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(submitButton)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void routingNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routingNumberTextActionPerformed
        // TODO add your handling code here:
        
        //The change typed in the routing number text fields in the UI is saved to the AutoPaymentList.
        
        String newRoutingNumber=routingNumberText.getText();
        list.get(currentAutoPayment).setRoutingNumber(newRoutingNumber);
        
        apl.setAutoPaymentList(list);
        
    }//GEN-LAST:event_routingNumberTextActionPerformed

    private void accountNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumberTextActionPerformed
        // TODO add your handling code here:
        
        //The change typed in the account number text fields in the UI is saved to the AutoPaymentList.
        
        String newBankAccountNumber=accountNumberText.getText();
        list.get(currentAutoPayment).setBankAccountNumber(newBankAccountNumber);
        
        apl.setAutoPaymentList(list);
        
    }//GEN-LAST:event_accountNumberTextActionPerformed

    private void autoPayAmountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoPayAmountTextActionPerformed
        // TODO add your handling code here:
        
        //The change typed in the payment amount text fields in the UI is saved to the AutoPaymentList.
        
        String newPaymentAmount=autoPayAmountText.getText();
        list.get(currentAutoPayment).setPaymentAmount(newPaymentAmount);
        
        apl.setAutoPaymentList(list);
    }//GEN-LAST:event_autoPayAmountTextActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        
        //The changes typed in the above text fields in the UI are saved to the AutoPaymentList.
        
            String newRoutingNumber=routingNumberText.getText();
            String newBankAccountNumber=accountNumberText.getText();
            String newPaymentAmount=autoPayAmountText.getText();
            
            list.get(currentAutoPayment).setRoutingNumber(newRoutingNumber);
            list.get(currentAutoPayment).setBankAccountNumber(newBankAccountNumber);
            list.get(currentAutoPayment).setPaymentAmount(newPaymentAmount);
            
            apl.setAutoPaymentList(list);
    }//GEN-LAST:event_submitButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField accountNumberText;
    public javax.swing.JTextField autoPayAmountText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField routingNumberText;
    public javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
